package com.phonefo.phone.service;

import java.util.List;

import com.phonefo.phone.domain.NoVO;
import com.phonefo.phone.domain.PhoneCapaVO;
import com.phonefo.phone.domain.PhoneColorVO;
import com.phonefo.phone.domain.PhoneInfoVO;
import com.phonefo.phone.domain.spec_audioVO;
import com.phonefo.phone.domain.spec_batteryVO;
import com.phonefo.phone.domain.spec_cameraVO;
import com.phonefo.phone.domain.spec_connectVO;
import com.phonefo.phone.domain.spec_displayVO;
import com.phonefo.phone.domain.spec_memoryVO;
import com.phonefo.phone.domain.spec_networkVO;
import com.phonefo.phone.domain.spec_processorVO;
import com.phonefo.phone.domain.spec_serviceVO;
import com.phonefo.phone.domain.spec_specificationsVO;

public interface PhoneInfoService {
	public List<PhoneInfoVO> selectInfo(String manufacture)throws Exception;
	public List<PhoneColorVO> select_color(int no)throws Exception;
	public List<PhoneCapaVO> select_capacity(int no)throws Exception;
	public spec_processorVO select_spec_processor(int no)throws Exception;
	public spec_displayVO select_spec_display(int no)throws Exception;
	public spec_cameraVO select_spec_camera(int no)throws Exception;
	public spec_memoryVO select_spec_memory(int no)throws Exception;
	public spec_networkVO select_spec_network(int no)throws Exception;
	public spec_connectVO select_spec_connect(int no)throws Exception;
	public spec_specificationsVO select_spec_specifications(int no)throws Exception;
	public spec_batteryVO select_spec_battery(int no)throws Exception;
	public spec_audioVO select_spec_audio(int no)throws Exception;
	public spec_serviceVO select_spec_service(int no)throws Exception;
	public PhoneInfoVO select_phone(int no)throws Exception;
	public void insert_phone(PhoneInfoVO phoneinfoVO)throws Exception;
	public int selectno()throws Exception;
	public void insert_color(PhoneColorVO phonecolorVO)throws Exception;
	public void insert_capacity(PhoneCapaVO phonecapaVO)throws Exception;
	public void insert_processor(spec_processorVO processorVO)throws Exception;
	public void insert_display(spec_displayVO displayVO)throws Exception;
	public void insert_camera(spec_cameraVO cameraVO)throws Exception;
	public void insert_memory(spec_memoryVO memoryVO)throws Exception;
	public void insert_network(spec_networkVO networkVO)throws Exception;
	public void insert_connect(spec_connectVO connectVO)throws Exception;
	public void insert_specifications(spec_specificationsVO specificationsVO)throws Exception;
	public void insert_battery(spec_batteryVO batteryVO)throws Exception;
	public void insert_audio(spec_audioVO audioVO)throws Exception;
	public void insert_service(spec_serviceVO serviceVO)throws Exception;
	public void update_phone(PhoneInfoVO phoneinfoVO)throws Exception;
//	public void update_color(PhoneColorVO phonecolorVO)throws Exception;
//	public void update_capacity(PhoneCapaVO phonecapaVO)throws Exception;
	public void update_processor(spec_processorVO processorVO)throws Exception;
	public void update_display(spec_displayVO displayVO)throws Exception;
	public void update_camera(spec_cameraVO cameraVO)throws Exception;
	public void update_memory(spec_memoryVO memoryVO)throws Exception;
	public void update_network(spec_networkVO networkVO)throws Exception;
	public void update_connect(spec_connectVO connectVO)throws Exception;
	public void update_specifications(spec_specificationsVO specificationsVO)throws Exception;
	public void update_battery(spec_batteryVO batteryVO)throws Exception;
	public void update_audio(spec_audioVO audioVO)throws Exception;
	public void update_service(spec_serviceVO serviceVO)throws Exception;
	public void delete_phone(int no)throws Exception;
	public void delete_color(int no)throws Exception;
	public void delete_capacity(int no)throws Exception;
	public void delete_processor(int no)throws Exception;
	public void delete_display(int no)throws Exception;
	public void delete_camera(int no)throws Exception;
	public void delete_memory(int no)throws Exception;
	public void delete_network(int no)throws Exception;
	public void delete_connect(int no)throws Exception;
	public void delete_specifications(int no)throws Exception;
	public void delete_battery(int no)throws Exception;
	public void delete_audio(int no)throws Exception;
	public void delete_service(int no)throws Exception;
	public List<PhoneInfoVO> selectnew() throws Exception;
}
